@startuml
skinparam SwimlaneTitleFontStyle bold

|s| Parallelized by sample
|i| Parallelized by interval

|s|
start

:'Validate input (PipeVal)';

:'Extract chromosome list (extract_GenomeIntervals)';

if (parallelize_by_chromosome?) then (Yes)
    :'SplitIntervals (by chromosome)';
else (No)
    :'SplitIntervals (scatter_count)';
endif

if (run_indel_realignment?) then (Yes)
    |i|
    :'RealignerTargetCreator_GATK';
    :'IndelRealigner_GATK';
    |s|
else (No)
    :'Use original BAMs';
endif

if (run_base_recalibration?) then (Yes)
    |i|
    :'BaseRecalibrator_GATK';
    :'GatherBQSRReports_GATK';
    :'ApplyBQSR_GATK';
    |s|
endif

:'Interval BAMs';

if (parallelize_by_chromosome?) then (Yes)
    :'GatherBamFiles_Picard (chromosome order from dict)';
else (No)
    :'MergeSamFiles_Picard';
    :'Deduplicate_records_SAMtools';
endif

:'Index BAM (samtools index)';

:'calculate_sha512';

fork
    :'GetPileupSummaries_GATK';
    :'CalculateContamination_GATK';
fork again
    if (run_DepthOfCoverage?) then (Yes)
        :'DepthOfCoverage_GATK';
    endif
end fork

stop
@enduml

