---
on:
  push:
    branches:
      - main
      - nwiltsie-nextflow-tests
  pull_request:
    branches:
      - main

jobs:
  nextflow_tests_job:
    uses: uclahs-cds/tool-Nextflow-action/.github/workflows/nextflow-tests.yml@nwiltsie-nextflow-regression-action
