---
on:
  push:
    branches:
      - main
      - nwiltsie-nextflow-tests
  pull_request:
    branches:
      - main

jobs:
  nextflow_tests_job:
    uses: uclahs-cds/tool-Nextflow-action/run-nextflow-tests/workflow.yml@nwiltsie-nextflow-regression-action
