# https://github.com/peter-evans/slash-command-dispatch/blob/a1f5efae7cc1f6c46ef1d02b5ce4710c716907aa/.github/workflows/slash-command-dispatch.yml
---
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/fix-tests') }}
    uses: uclahs-cds/tool-Nextflow-action/.github/workflows/nextflow-tests.yml@nwiltsie-autofix-tests
